.nh
.TH "GH-EXTENSION-LIST" "1" "Aug 2024" "GitHub CLI 2.54.0" "GitHub CLI manual"

.SH NAME
.PP
gh-extension-list - List installed extension commands


.SH SYNOPSIS
.PP
\fBgh extension list [flags]\fR


.SH ALIASES
.PP
gh ext ls, gh extension ls, gh extensions ls


.SH SEE ALSO
.PP
\fBgh-extension(1)\fR
